"""
add_multitenancy_support

Revision ID: d7fe42b0ac1c
Revises: a1b2c3d4e5f6
Create Date: 2026-01-12 12:23:44.545240
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7fe42b0ac1c'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_positive', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('correction', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_request_id'), 'feedbacks', ['request_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_tenant_id'), 'feedbacks', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key_prefix', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_api_key_prefix'), 'tenants', ['api_key_prefix'], unique=True)
    op.create_table('api_key_tenants',
    sa.Column('api_key_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('api_key_id', 'tenant_id')
    )
    op.drop_index(op.f('ix_benchmark_runs_status'), table_name='benchmark_runs')
    
    # Safe add tenant_id to chunks
    op.add_column('chunks', sa.Column('tenant_id', sa.String(), nullable=True))
    op.execute("UPDATE chunks SET tenant_id = documents.tenant_id FROM documents WHERE chunks.document_id = documents.id")
    op.execute("UPDATE chunks SET tenant_id = 'default' WHERE tenant_id IS NULL")
    op.alter_column('chunks', 'tenant_id', nullable=False)
    op.create_index(op.f('ix_chunks_tenant_id'), 'chunks', ['tenant_id'], unique=False)

    op.alter_column('folders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"))
    op.alter_column('folders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"))

    # Enable RLS Policies
    op.execute("ALTER TABLE documents ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY tenant_isolation_documents ON documents USING (tenant_id = current_setting('app.current_tenant')::text)")

    op.execute("ALTER TABLE chunks ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY tenant_isolation_chunks ON chunks USING (tenant_id = current_setting('app.current_tenant')::text)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop RLS Policies
    op.execute("DROP POLICY IF EXISTS tenant_isolation_chunks ON chunks")
    op.execute("ALTER TABLE chunks DISABLE ROW LEVEL SECURITY")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_documents ON documents")
    op.execute("ALTER TABLE documents DISABLE ROW LEVEL SECURITY")
    op.alter_column('folders', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"))
    op.alter_column('folders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"))
    op.drop_index(op.f('ix_chunks_tenant_id'), table_name='chunks')
    op.drop_column('chunks', 'tenant_id')
    op.create_index(op.f('ix_benchmark_runs_status'), 'benchmark_runs', ['status'], unique=False)
    op.drop_table('api_key_tenants')
    op.drop_index(op.f('ix_tenants_api_key_prefix'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_feedbacks_tenant_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_request_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
