"""
create_connector_states_table

Revision ID: f40c9184d431
Revises: 023abc5b6e16
Create Date: 2026-01-09 14:20:35.007900
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f40c9184d431'
down_revision: Union[str, None] = '023abc5b6e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('connector_states',
    # sa.Column('id', sa.String(), nullable=False),
    # sa.Column('tenant_id', sa.String(), nullable=False),
    # sa.Column('connector_type', sa.String(), nullable=False),
    # sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    # sa.Column('sync_cursor', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    # sa.Column('status', sa.String(), nullable=False),
    # sa.Column('error_message', sa.String(), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_connector_states_id'), 'connector_states', ['id'], unique=False)
    # op.create_index(op.f('ix_connector_states_tenant_id'), 'connector_states', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_connector_states_tenant_id'), table_name='connector_states')
    # op.drop_index(op.f('ix_connector_states_id'), table_name='connector_states')
    # op.drop_table('connector_states')
    # ### end Alembic commands ###
    pass
