"""
add_golden_status_to_feedback

Revision ID: e0f3580058d2
Revises: 7c3de6839ce1
Create Date: 2026-01-14 11:20:01.203680
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e0f3580058d2'
down_revision: Union[str, None] = '7c3de6839ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('golden_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_feedbacks_golden_status'), 'feedbacks', ['golden_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_golden_status'), table_name='feedbacks')
    op.drop_column('feedbacks', 'golden_status')
    # ### end Alembic commands ###
