"""
Add memory tables

Revision ID: 44be9e58de47
Revises: f9ab45c6d7e8
Create Date: 2026-01-06 15:02:43.513070
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44be9e58de47'
down_revision: Union[str, None] = 'f9ab45c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conv_summaries_tenant_user_date', 'conversation_summaries', ['tenant_id', 'user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_tenant_id'), 'conversation_summaries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_user_id'), 'conversation_summaries', ['user_id'], unique=False)
    op.create_table('user_facts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_facts_tenant_id'), 'user_facts', ['tenant_id'], unique=False)
    op.create_index('ix_user_facts_tenant_user', 'user_facts', ['tenant_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_user_facts_user_id'), 'user_facts', ['user_id'], unique=False)
    # NOTE: Removed unintended DROP TABLE statements for benchmark_runs and connector_states
    # that were auto-generated due to schema drift. Those tables should remain intact.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Simplified to only remove memory tables.
    # Removed recreation of benchmark_runs and connector_states tables
    # since we no longer drop them in upgrade.
    op.drop_index(op.f('ix_user_facts_user_id'), table_name='user_facts')
    op.drop_index('ix_user_facts_tenant_user', table_name='user_facts')
    op.drop_index(op.f('ix_user_facts_tenant_id'), table_name='user_facts')
    op.drop_table('user_facts')
    op.drop_index(op.f('ix_conversation_summaries_user_id'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_tenant_id'), table_name='conversation_summaries')
    op.drop_index('ix_conv_summaries_tenant_user_date', table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    # ### end Alembic commands ###

